# Check script 

name: Check action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0 10 * * 6'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pillow pytesseract requests
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
        SERVER: ${{ secrets.Server }}
        MAILPASS: ${{ secrets.Mailpass }}
        RECEIVER: ${{ secrets.Receiver }}
      run: |
        python checkUpload.py "$STUID" "$PASSWORD"
